// test/seed.js
// Seed dummy data into MySQL for the uptime monitoring system.

const mysql = require('mysql2/promise');

(async () => {
  const pool = mysql.createPool({
    host: 'localhost',
    user: 'root',
    password: '12345',
    database: 'sitechecker',
    waitForConnections: true,
    connectionLimit: 5,
    queueLimit: 0
  });

    const dummyWebsites = [
      { url: 'https://example.com', interval_seconds: 60 },
      { url: 'https://chesapeakelibraryfoundation.org', interval_seconds: 60 },
      { url: 'https://cieesodu.org', interval_seconds: 60 },
      { url: 'https://influancehaircare.com', interval_seconds: 60 },
      { url: 'https://learn.ttac.odu.edu', interval_seconds: 60 },
      { url: 'https://norfolkbotanicalgarden.org', interval_seconds: 60 },
      { url: 'https://ttac.odu.edu', interval_seconds: 60 },
      { url: 'https://foodbankonline.org', interval_seconds: 60 },
      { url: 'https://bluewatergrillobx.com', interval_seconds: 60 },
      { url: 'https://hamptonroadscf.org', interval_seconds: 60 },
      { url: 'https://mileminded.com', interval_seconds: 60 },
      { url: 'https://marybarnetts.com', interval_seconds: 60 },
      { url: 'https://vbnationalonthegreen.com', interval_seconds: 60 },
      { url: 'https://winnersmarketinginc.com', interval_seconds: 60 },
      { url: 'https://oasissocialministry.org', interval_seconds: 60 },
      { url: 'https://leesfriends.org', interval_seconds: 60 },
      { url: 'https://battlefieldpharmacyrx.com', interval_seconds: 60 },
      { url: 'https://rashmibhattdds.com', interval_seconds: 60 },
      { url: 'https://cpmlawplc.com', interval_seconds: 60 },
      { url: 'https://co-technologies.com', interval_seconds: 60 },
      { url: 'http://associatesingastro.com', interval_seconds: 60 },
      { url: 'http://daytongastro.com', interval_seconds: 60 },
      { url: 'http://dhsgi.net', interval_seconds: 60 },
      { url: 'http://doctorgi.com', interval_seconds: 60 },
      { url: 'http://franklingastroenterology.com', interval_seconds: 60 },
      { url: 'http://ganm.net', interval_seconds: 60 },
      { url: 'http://gastro1.com', interval_seconds: 60 },
      { url: 'http://gastrohealthpartners.com', interval_seconds: 60 },
      { url: 'http://gatgi.com', interval_seconds: 60 },
      { url: 'http://ghscanton.com', interval_seconds: 60 },
      { url: 'http://greatlakesgastro.net', interval_seconds: 60 },
      { url: 'http://loudouncslcenter.com', interval_seconds: 60 },
      { url: 'http://mid-stategastro.com', interval_seconds: 60 },
      { url: 'http://mygidocs.com', interval_seconds: 60 },
      { url: 'http://onegi.com', interval_seconds: 60 },
      { url: 'http://skylinegastro.com', interval_seconds: 60 },
      { url: 'https://barryartmuseum.odu.edu', interval_seconds: 60 },
      { url: 'https://jsrussell.org', interval_seconds: 60 },
      { url: 'https://commandposttech.com', interval_seconds: 60 },
      { url: 'https://hutchinsonlawcenter.com', interval_seconds: 60 },
      { url: 'https://centumnow.com', interval_seconds: 60 },
      { url: 'https://michaelriverssr.com', interval_seconds: 60 },
      { url: 'https://tucincva.com', interval_seconds: 60 },
      { url: 'https://myinvictussales.com', interval_seconds: 60 },
      { url: 'https://providenceriskadvisors.com', interval_seconds: 60 },
      { url: 'https://meetmeinparis.com', interval_seconds: 60 },
      { url: 'https://vtff.org', interval_seconds: 60 },
      { url: 'https://veritastherapeuticsvirginia.com', interval_seconds: 60 },
      { url: 'https://sitewon.com', interval_seconds: 60 },
      { url: 'https://babbtothehome.com', interval_seconds: 60 },
      { url: 'https://annasristorantepastavinopizza.com', interval_seconds: 60 },
      { url: 'https://documentation.gotechark.com', interval_seconds: 60 },
      { url: 'https://nnparksandrec.org', interval_seconds: 60 },
      { url: 'https://ywca-shr.org', interval_seconds: 60 },
      { url: 'https://landmarkhotelgroup.com', interval_seconds: 60 },
      { url: 'https://cavalierland.com', interval_seconds: 60 },
      { url: 'https://spaandlasercenter.com', interval_seconds: 60 },
      { url: 'https://strelitzinternationalacademy.org', interval_seconds: 60 },
      { url: 'https://century-concrete.com', interval_seconds: 60 },
      { url: 'https://nehasvegankitchen.com', interval_seconds: 60 },
      { url: 'https://pro-vost.com', interval_seconds: 60 },
      { url: 'https://wccarpenter.com', interval_seconds: 60 },
      { url: 'https://cceva.org', interval_seconds: 60 },
      { url: 'https://mixandshine.com', interval_seconds: 60 },
      { url: 'https://jiffyknee.com', interval_seconds: 60 },
      { url: 'https://thewilliamsschool.org', interval_seconds: 60 },
      { url: 'https://memorialbeachchallenge.com', interval_seconds: 60 },
      { url: 'https://eoseva.org', interval_seconds: 60 },
      { url: 'https://fastech-engineering.com', interval_seconds: 60 },
      { url: 'https://kelleterlaw.com', interval_seconds: 60 },
      { url: 'https://usfutaba.com', interval_seconds: 60 },
      { url: 'https://kittoplasticsurgery.com', interval_seconds: 60 },
      { url: 'https://archbellsigns.com', interval_seconds: 60 },
      { url: 'https://mahisvb.com', interval_seconds: 60 },
      { url: 'https://rivercityenterprises.net', interval_seconds: 60 },
      { url: 'https://earlychildhoodpdva.org', interval_seconds: 60 },
      { url: 'https://thekairosgroup.com', interval_seconds: 60 },
      { url: 'https://visitcova.com', interval_seconds: 60 },
      { url: 'https://mountaineerins.com', interval_seconds: 60 },
      { url: 'https://rds-virginia.com', interval_seconds: 60 },
      { url: 'https://tcsmusicfoundation.org', interval_seconds: 60 },
      { url: 'https://redefyflatfee.com', interval_seconds: 60 },
      { url: 'https://504capital.com', interval_seconds: 60 },
      { url: 'https://escsb.org', interval_seconds: 60 },
      { url: 'https://atlanticdominiondistributors.com', interval_seconds: 60 },
      { url: 'https://emc-co.com', interval_seconds: 60 },
      { url: 'https://sparoma.com', interval_seconds: 60 },
      { url: 'https://oceanmarineinc.com', interval_seconds: 60 },
      { url: 'https://southernpineapts.com', interval_seconds: 60 },
      { url: 'https://elitewomenscare.com', interval_seconds: 60 },
      { url: 'https://midatlanticentry.com', interval_seconds: 60 },
      { url: 'https://bvifreedom.com', interval_seconds: 60 },
      { url: 'https://admiralsignworks.com', interval_seconds: 60 },
      { url: 'https://readysetregisterse.org', interval_seconds: 60 },
      { url: 'https://chb360.com', interval_seconds: 60 },
      { url: 'https://pambakerllc.com', interval_seconds: 60 },
      { url: 'https://obgynofhampton.com', interval_seconds: 60 },
      { url: 'https://yogibyheart.com', interval_seconds: 60 },
      { url: 'https://ironclad-evaluations.org', interval_seconds: 60 },
      { url: 'https://twohundredwest.com', interval_seconds: 60 },
      { url: 'https://currituckgamecommission.com', interval_seconds: 60 },
      { url: 'https://integritycoatingconsultants.com', interval_seconds: 60 },
      { url: 'https://agwraps.com', interval_seconds: 60 },
      { url: 'https://albemarleeye.com', interval_seconds: 60 },
      { url: 'https://amaramd.com', interval_seconds: 60 },
      { url: 'https://app.designonespace.com', interval_seconds: 60 },
      { url: 'https://arts4learningva.org', interval_seconds: 60 },
      { url: 'https://beachtherapyandconsulting.com', interval_seconds: 60 },
      { url: 'https://careerpathways.allanmyers.com', interval_seconds: 60 },
      { url: 'https://carolinaeyecare.com', interval_seconds: 60 },
      { url: 'https://ceapodu.com', interval_seconds: 60 },
      { url: 'https://cebisva.org', interval_seconds: 60 },
      { url: 'https://centerforsight.net', interval_seconds: 60 },
      { url: 'https://cfsfoundation.org', interval_seconds: 60 },
      { url: 'https://cfssurgicalcenter.com', interval_seconds: 60 },
      { url: 'https://charlestoneyesurgery.com', interval_seconds: 60 },
      { url: 'https://vastudentservices-clc.org', interval_seconds: 60 },
      { url: 'https://dchfa.org', interval_seconds: 60 },
      { url: 'https://designonespace.com', interval_seconds: 60 },
      { url: 'https://www.egglestonservices.org', interval_seconds: 60 },
      { url: 'https://etgresham.com', interval_seconds: 60 },
      { url: 'https://illuminatingshadows.org', interval_seconds: 60 },
      { url: 'https://gardenoftomorrow.org', interval_seconds: 60 },
      { url: 'https://www.glasserlaw.com', interval_seconds: 60 },
      { url: 'https://gotechark.com', interval_seconds: 60 },
      { url: 'https://griffey2020.com', interval_seconds: 60 },
      { url: 'https://www.havtech.com', interval_seconds: 60 },
      { url: 'https://iavva.com', interval_seconds: 60 },
      { url: 'https://ingyouth.org', interval_seconds: 60 },
      { url: 'https://ing.org', interval_seconds: 60 },
      { url: 'https://ita-intl.com', interval_seconds: 60 },
      { url: 'https://vafamlaw.com', interval_seconds: 60 },
      { url: 'https://www.kaufcan.com', interval_seconds: 60 },
      { url: 'https://lakeeye.com', interval_seconds: 60 },
      { url: 'https://learning.cebisva.org', interval_seconds: 60 },
      { url: 'https://maulik.tekark.com', interval_seconds: 60 },
      { url: 'https://mealsonwheelschesapeake.com', interval_seconds: 60 },
      { url: 'https://newportnewshistory.org', interval_seconds: 60 },
      { url: 'https://norfolkdevelopment.com', interval_seconds: 60 },
      { url: 'https://oduadaptationandresilience.org', interval_seconds: 60 },
      { url: 'https://osep.cieesodu.org', interval_seconds: 60 },
      { url: 'https://www.pancopia.com', interval_seconds: 60 },
      { url: 'https://projecthopevirginia.org', interval_seconds: 60 },
      { url: 'https://projects-tracker.tekark.com', interval_seconds: 60 },
      { url: 'https://www.retinahealthcenter.com', interval_seconds: 60 },
      { url: 'https://revive.cieesodu.org', interval_seconds: 60 },
      { url: 'https://rrsefoundationaltraining.minus9to5.org', interval_seconds: 60 },
      { url: 'https://s23holdings.com', interval_seconds: 60 },
      { url: 'https://www.scansamerica.com', interval_seconds: 60 },
      { url: 'https://securitytechnologygroup.com', interval_seconds: 60 },
      { url: 'https://secepcareers.net', interval_seconds: 60 },
      { url: 'https://spectrumenergyllc.com', interval_seconds: 60 },
      { url: 'https://steqtech.com', interval_seconds: 60 },
      { url: 'https://summitpointeva.com', interval_seconds: 60 },
      { url: 'https://my.gotechark.com', interval_seconds: 60 },
      { url: 'https://thehemppharmacist.com', interval_seconds: 60 },
      { url: 'https://titlequest.net', interval_seconds: 60 },
      { url: 'https://tullfinancial.com', interval_seconds: 60 },
      { url: 'https://useye.com', interval_seconds: 60 },
      { url: 'https://www.cvsesurgerycenter.com', interval_seconds: 60 },
      { url: 'https://www.swfleye.com', interval_seconds: 60 },
      { url: 'https://vamwa.org', interval_seconds: 60 },
      { url: 'https://vastudentservices.org', interval_seconds: 60 },
      { url: 'https://verdata.com', interval_seconds: 60 },
      { url: 'https://vfsworks.com', interval_seconds: 60 },
    ];
  const conn = await pool.getConnection();
  try {
    // Clean existing data
    await conn.query('DELETE FROM uptime_logs');
    await conn.query('DELETE FROM websites');
    // Insert dummy websites
    for (const site of dummyWebsites) {
      await conn.execute(
        'INSERT INTO websites (url, interval_seconds) VALUES (?, ?)',
        [site.url, site.interval_seconds]
      );
    }
    console.log('✅ Dummy website data inserted.');
  } finally {
    conn.release();
    await pool.end();
  }
})();
